# Generated by Django 4.2.11 on 2024-04-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_remove_round_match_date_remove_team_is_full_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournement',
            name='full',
            field=models.BooleanField(default=False),
        ),
    ]
