# Generated by Django 4.2.11 on 2024-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
        ('tournament', '0004_tournement_full'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournement',
            old_name='teams',
            new_name='number_of_teams',
        ),
        migrations.AddField(
            model_name='tournement',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='enrolled_tournaments', to='pong.usercustom'),
        ),
    ]
